project:
  type: book

book:
  title: "CM3"
  author: "Dr Chris Wheadon"
  date: "2/23/2023"
  chapters:
    - index.qmd
    - tools.qmd
    - verify.qmd
    - cj-intro.qmd
    - part: "Classical Test Theory"
      chapters:
        - setup.qmd
        - dataset.qmd
        - ct-test-1.qmd
        - demographics-1.qmd
        - ct-item-1.qmd
        - ct-item-discrimination-1.qmd
        - ct-item-total-1.qmd
        - ct-reliability.qmd
        - ct-alpha.qmd
    - part: "The Rasch Model"
      chapters:
        - rasch-1.qmd
        - rasch-2.qmd
      
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: true

