project:
  type: book

book:
  title: "CM3"
  author: "Dr Chris Wheadon"
  date: "2/23/2023"
  chapters:
    - index.qmd
    - tools.qmd
    - verify.qmd
    - cj-intro.qmd
    - part: "Classical Test Theory"
      chapters:
        - setup.qmd
        - dataset.qmd
        - c-test-information.qmd
        - demographics-1.qmd
      
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: true

