project:
  type: book

book:
  title: "CM3"
  author: "Dr Chris Wheadon"
  date: "2/23/2023"
  chapters:
    - index.qmd
    - tools.qmd
    - part: "Classical Test Theory"
      chapters:
        - setup.qmd
        - dataset.qmd
        - ct-test-1.qmd
        - demographics-1.qmd
        - ct-item-1.qmd
        - ct-item-discrimination-1.qmd
        - ct-item-discrimination-2.qmd
        - ct-item-total-1.qmd
        - ct-distractors.qmd
        - ct-reliability.qmd
        - ct-alpha.qmd
        - ct-dif.qmd
    - part: "The Rasch Model"
      chapters:
        - rasch-1.qmd
        - rasch-2.qmd
        - rasch-irt-two-param.qmd
        - rasch-regression.qmd
        - rasch-ability-difficulty.qmd
        - rasch-infit.qmd
        - rasch-dif.qmd
        - workshop.qmd
        - workshop-answers.qmd
    - part: "The Partial Credit Model"
      chapters:
        - pc-1.qmd
        - pc-thurstone.qmd
        - pc-expected.qmd
        - pc-2.qmd
    - part: "Comparative Judgement"
      chapters:
        - cj-bt-rasch.qmd
        - cj-practical.qmd
        - cj-equating.qmd
    - part: "Further Reading"
      chapters:
        - further-reading.qmd
        - references.qmd
      
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: true

nocite: |
  @*