# Ranks versus scaled scores

```{r}
#| warning: false
library(tidyverse)
library(nmmMongo)
connStr <- Sys.getenv("R_CONN")
task <- "4deb95e3-cefb-470f-b7f6-ca8564881197"
# task <- "989c5ad8-3682-4ad8-b8ba-c47fc49cc7c8"

persons <- nmmMongo::getPersonsFromTask(task, mod=FALSE, connStr)
# glimpse(persons)
# Add a rank column to the persons data frame
persons <- persons %>% arrange(scaledScore) %>% mutate(rank = row_number())
# select the scaledScore, lowerScaled, upperScaled, and rank columns
persons <- persons %>% select(scaledScore, lowerScaled, upperScaled,firstName,rank)
# filter out any missing values in any columns
persons <- persons %>% drop_na()

```

# Plot the scaled scores versus the ranks

```{r}
ggplot(persons, aes(x = rank, y = scaledScore)) +
geom_point() +
geom_errorbar(aes(ymin = lowerScaled, ymax = upperScaled), width = 0.2) +
labs(x = "Rank", y = "Scaled score") +
theme_bw()
```

# Plot the scaled scores versus the ranks with a linear regression line

```{r}
ggplot(persons, aes(x = rank, y = scaledScore)) +  
geom_point() +
geom_errorbar(aes(ymin = lowerScaled, ymax = upperScaled), width = 0.2) +
labs(x = "Rank", y = "Scaled score") +
theme_bw() +
geom_smooth(method = "lm", se = FALSE)
```

# Plot the scaled scores versus the ranks with a non linear regression line


```{r}
ggplot(persons, aes(x = rank, y = scaledScore)) +
geom_point() +
geom_errorbar(aes(ymin = lowerScaled, ymax = upperScaled), width = 0.2) +
labs(x = "Rank", y = "Scaled score") +
theme_bw() +
geom_smooth(method = "gam", se = FALSE)
```

