---
title: "Classical Test Analysis"
format: html
---

```{r}
#| label: setup
rm(list=ls())
library(tidyverse)
# load in the datasets
basePath = Sys.getenv("R_BASEFILE")
scores <- read_csv(here::here("data/2022-2023/ISW/ISW 2022-2023 Year 7 Jan", "scores.csv"))
```

## Test Information
    
```{r}
#| label: basic-stats
#| include: true
#| table-cap: Summary statistics for the scores
# table with number of candidates, mean, standard deviation, min and max
# round all stats to 2 decimal places
summary_table <- scores %>% 
  summarise(
    n = n(),
    mean = mean(score),
    sd = sd(score),
    min = min(score),
    max = max(score)
  )
knitr::kable(summary_table, digits = 2,align = "c")
```

# Score Distribution

```{r}
#| label: fig-histogram
#| fig-cap: Histogram of scores
#| width: 6
#| height: 4
#| include: true
ggplot (scores, aes(x = score)) +
  geom_histogram(bins = 21) +
  scale_x_continuous(breaks = seq(0, 20, 1)) +
  # add a vertical line at the mean
    geom_vline(xintercept = mean(scores$score), linetype = "dashed", color = "red") +
    # add the light theme
    theme_light() 


``` 

### What can we learn from the distribution of scores?

{{< pagebreak >}}

## Item Information