# Fitting the Partial Credit Model

You can fit the Partial Credit Model in either dexter or TAM. Let's start with dexter.

```{r}
#| include: true
#| echo: true
#| output: false
#| warning: false
rm(list=ls())
library(tidyverse)
library(dexter)
# load in the dataset
responses <- read_csv('data/pc-data.csv')
# recode NA as 0 across all columns
responses <- responses %>% 
  mutate_if(is.numeric, ~replace_na(., 0))
# load the data summary
data_summary <- read_csv('data/pc-data-summary.csv')
```

```{r}
#| include: true
#| echo: true
#| output: false
#| warning: false
# Create the rules from the summary
# create an empty tibble with three columns item_id, response, and item_score
rules <- tibble(item_id = character(), response = character(), item_score = numeric())

# for each row in the data summary create a rule
for (i in 1:nrow(data_summary)) {
  # get the item id
  item_id <- data_summary$Variable[i]
  # get the maximum mark
  max_mark <- data_summary$`Maximum possible mark`[i]
  # for every mark from 0 to max_mark create a rule
    for (mark in 0:max_mark) {
        # create a rule for the mark
        rule <- tibble(item_id = item_id, response = as.character(mark), item_score = mark)
        # add the rule to the rules tibble
        rules <- bind_rows(rules, rule)
    }
}
```

```{r}
#| include: true
#| echo: true
#| output: true
#| warning: false
# create a new project
db <- start_new_project(rules, db_name = ":memory:", person_properties=list(sex="unknown",grade="unknown"))
# add the response data
add_booklet(db, responses, "geography")
```

```{r}
#| include: true
#| echo: true
#| output: true
#| warning: false
# print the item tables
tt = tia_tables(db)
knitr::kable(tt$items, digits=2)
```

## Expected Score Curves

```{r}
#| include: true
#| echo: true
#| output: true
#| warning: false
m = fit_inter(db)
n_items <- nrow(data_summary)
for(i in 1:n_items){
    plot(m, data_summary$Variable[i], show.observed=TRUE)
}

```

## Item Difficulty

```{r}
#| include: true
#| echo: true
#| output: true
#| warning: false
m = fit_inter(db)
n_items <- nrow(data_summary)
for(i in 1:n_items){
    plot(m, data_summary$Variable[i], summate=FALSE, show.observed=FALSE)
}

# plot(m, "C3_1ai", summate=FALSE, show.observed=FALSE)
# plot(m, "C3_1ai", summate=TRUE, show.observed=TRUE)

close_project(db)
```

```{r}

```

## Take a look at the SPAG items. How well are they working?