# Fitting the Partial Credit Model with TAM
## Items in section 1, C1_
```{r}
#| include: true
#| echo: true
#| output: false
#| warning: false
rm(list=ls())
library(TAM)
library(WrightMap)
library(tidyverse)

# load in the dataset
responses <- read_csv('data/pc-data.csv')
# drop the first six columns
resp <- responses %>% 
  select(-c(1:6))
# choose the columns that start with C1_
resp_c1 <- resp %>% 
  select(starts_with('C1_'))

mod1 <- tam.jml(resp_c1)

thres <- tam.threshold(mod1) # find Thurstonian thresholds

wrightMap(mod1$WLE, thres, item.side = itemClassic)
wrightMap(mod1$WLE, thres)  # try different display options

plot(mod1)  #Expected score curves
plot(mod1,type="items")  #ICCs

knitr::kable(mod1$item1)  #show item parameters (deltas)
```

## Things to consider
Are there items with disordered thresholds? Why might this be?
Are there any misfitting items? Why might this be?
How well targeted is the test?

## Extension exercises
Try CM2 and CM3 by changing the code to select items that start with C2_ or C3_

```{r}
#| include: true
#| echo: true
#| output: false
#| warning: false
resp_c2 <- resp %>% 
  select(starts_with('C2_'))
```
